apiVersion: v1
kind: Service
metadata:
  name: score-controller-service
spec:
  selector:
    app: score-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
