name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Start LocalStack
        run: docker run -d --name localstack -e SERVICES=dynamodb -p 4566:4566 localstack/localstack:latest

      - name: Wait for LocalStack to be ready
        run: |
          until curl -sS http://localhost:4566; do
            sleep 2
          done

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region eu-west-2
        env:
          AWS_DEFAULT_REGION: eu-west-2

      - name: Build and Verify
        run: |
          ./mvnw clean verify
        working-directory: ./

      - name: Check Build Status
        id: build-status
        if: success()
        run: echo "Build and Verify completed successfully!"