name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region eu-west-2
        env:
          AWS_DEFAULT_REGION: eu-west-2

      - name: Build and Verify
        run: |
          ./mvnw clean verify
        working-directory: ./

      - name: Check Build Status
        id: build-status
        run: echo "Build and Verify completed successfully!"

      - name: Set Build Status
        if: success()
        run: gh pr merge $GITHUB_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
